### ISSUE TITLE
Release date?

### ISSUE THREAD

**Issue by synhershko** [floragunncom/search-guard-module-auditlog#1]
Docs say July, but last commit was June 20th. Is there a planned release date?

**Comment by floragunn** [comment]
Hi! We released SG2 alongside with all enterprise features on June, 17th. The audit log module was included in this release as well. However, the docs are still lacking a chapter about audit logging, thanks for bringing that to our attention. We're working on updating the docs.

**Comment by synhershko** [comment]
Thanks for the clarification. We are interested in auditing all ES access (so search & get access as well, not only logins and indexing attempts). Is this a feature you will be willing to add?

**Comment by floragunn** [comment]
I'm positive, since the necessary changes are relatively small. Let me talk with the team tomorrow and see where it fits in on our feature road map. I'll leave this issue open and comment once I got feedback.

**Comment by synhershko** [comment]
Cool, thanks

**Comment by floragunn** [comment]
We have added the extended configuration of the audit log module to the next sprint. You can expect it to be released in the next 2-4 weeks.

**Comment by floragunn** [comment]
will merge and include in next release
