### ISSUE TITLE
Missing audit_request_headers and audit_request_path from audit log for AUTHENTICATED category

### ISSUE THREAD

**Issue by elaPa** [floragunncom/search-guard-module-auditlog#13]
I'm evaluating search-guard audit module.
My requirement is to be able to log audit token which is included in the header of all http requests to Elasticsearch.

I can see the following:
For FAILED_LOGIN requests:

> AUDIT_LOG:
 {
  "audit_date" : "Wed Aug 09 16:59:29 UTC 2017",
  "audit_remote_address" : "172.17.0.1:53624",
  "audit_request_path" : "/searchguard/_search",
  "audit_format_version" : 2,
  "audit_utc_timestamp" : "2017-08-09T16:59:29.970+00:00",
  "audit_request_type" : "rest",
  "audit_request_headers" : "[Host=localhost:9200, Authorization=Basic YWRtaW46YWRtWFg=, User-Agent=curl/7.54.0, Accept=*/*, Audit-log=123, Content-Length=45, Content-Type=application/x-www-form-urlencoded]",
  "audit_principal" : null,
  "audit_details" : "admin",
  "audit_category" : "FAILED_LOGIN",
  "audit_request_user" : null,
  "audit_request_class" : "class org.elasticsearch.http.netty4.Netty4HttpRequest",
  "audit_reason" : "User: admin"
}

 

 I have all information I need included in the log there.

But for AUTHENTICATED request:
>AUDIT_LOG: {
  "audit_date" : "Wed Aug 09 16:59:42 UTC 2017",
  "audit_remote_address" : "172.17.0.1:53626",
  "audit_format_version" : 2,
  "audit_utc_timestamp" : "2017-08-09T16:59:42.452+00:00",
  "audit_request_type" : "transport",
  "audit_request_headers" : "{}",
  "audit_principal" : null,
  "audit_details" : "indices:data/read/search",
  "audit_category" : "AUTHENTICATED",
  "audit_request_user" : "admin",
  "audit_request_class" : "class org.elasticsearch.action.search.SearchRequest",
  "audit_reason" : "Action: indices:data/read/search"
}

The `audit_request_headers` is empty. 
Is this intentional? Is there any way to enable it?

Also, the `audit_request_path` is not included in the AUTHENTICATED log. It is useful to indicate, what was the type of the request (eg search) and which index / type was targeted.
Is there a way to include this as well?

Thank you.

**Comment by floragunn** [comment]
Will look into this ...

**Comment by floragunn** [comment]
the second auditlog message is a "transport" layer message, not a REST layer message which naturally has nothing such an HTTP header. The transport layer is mainly for inter node communication. Not sure if this is relevant for you.

**Comment by floragunn** [comment]
No response, will close ...
