### ISSUE TITLE
Audit module is not working with searchguard-2 v2.3.5.5

### ISSUE THREAD

**Issue by catalinvr** [floragunncom/search-guard-module-auditlog#4]
Hello,

I try to enable the audit module and I received a Java Error.
Now I'm using a two node cluster with searchguard-ssl v2.3.5.15 and searchguard-2 v2.3.5.5

I have downloaded the jar and installed intro the es_path. After I restart the elasticsearch service I receive the following error: http://pastebin.com/qVuKdZkN

Everything is ok when I remove the jar file.

The version of the auditlog module is not compatible with searchguard-2 ?

Here is the elasticsaerch configuration: http://pastebin.com/eaGHFgpf

Thanks,
Catalin

**Comment by floragunn** [comment]
Thanks for reporting. Audit logging should be compatible with 2.3.3.5. We'll have a look into this.

**Comment by floragunn** [comment]
Just to make sure, which version of the audit log module are you using?

**Comment by catalinvr** [comment]
I'm using the auditlog v2.3.3.1 from http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22com.floragunn%22%20AND%20a%3A%22dlic-search-guard-module-auditlog%22

**Comment by floragunn** [comment]
When you're saying you installed it into es_path, what exacatly do you mean? Because the jar has to go into this folder: <ES installation directory>/plugins/search-guard-2/

**Comment by catalinvr** [comment]
Into the _/usr/share/elasticsearch/plugins/search-guard-2_ directory

**Comment by catalinvr** [comment]
[2016-09-16 13:50:26,804][INFO ][com.floragunn.searchguard.auditlog.AuditLogModule] Auditlog available (AuditLogImpl)

Seems that the jar file is found by searchguard-2

**Comment by floragunn** [comment]
Seems there is a conflict with the ES license plugin you have installed. We usually do not test Search Guard with the commercial ES features installed, because if you bought a license from ES, you'd use Shield instead of SG. Do you explicitely need the license plugin?

**Comment by catalinvr** [comment]
No, I will remove it and restart the cluster.
I will get back to you soon with any update on this.
Thank you

**Comment by catalinvr** [comment]
Now is working. Many thanks !!!

**Comment by floragunn** [comment]
Glad to help and thanks for using Search Guard. Just remember that audit logging is an enterprise feature, so you'd need a licence for commercial projects.

**Comment by laf-rge** [comment]
I use the free version of Marvel so I have the license plugin installed. Would this still be an issue?

**Comment by catalinvr** [comment]
Yes, for searchguard-2 v2.3.5.5. You can use Kopf. Also is needed to remove license plugin from elasticsearch.

**Comment by floragunn** [comment]
We are working on making auditlog work with license/marvel plugin

**Comment by laf-rge** [comment]
Thanks. Is there an issue I can subscribe to?

**Comment by floragunn** [comment]
its already fixed in the most recent release (install latest searchguard and latest auditlog module version)
