### ISSUE TITLE
Date in ES supported format and mappings

### ISSUE THREAD

**Issue by matejzero** [floragunncom/search-guard-module-auditlog#6]
Hello,

I've just played around with auditlog module and noticed that index can't be add as 'time-based events index'. Looking at the mapping and data stored, I can see why.

I think it would be good to change the time format to ES supported one (eg. basic_date_time - 2016-12-27T06:08:46.374Z) and also create a basic mapping for auditlog index (not all fields need to be analyzed and timestamp field should be set to date format instead of text/keyword,...).

Comments?

**Comment by matejzero** [comment]
I tried parsing the current date with date format set in the mappings but it won't work because of zone names, which are not uniq.

Quote from joda lib:

> Zone names: Time zone names ('z') cannot be parsed.

Issue  #[16486](https://github.com/elastic/elasticsearch/issues/16486) on ES github page explains it.

**Comment by matejzero** [comment]
Never mind, I noticed you added audit_utc_timestamp to the module but it's not in the latest release yet. I downloaded the es-5.0 branch and compiled the module and it's working:)

Looking at the mapping, I think we can live the the default one, almost all fields are useful analyzed anyway.

Closing...

**Comment by floragunn** [comment]
We are working on the Auditlog module currently as you already noticed :-)

**Comment by floragunn** [comment]
Expect a new release during first week of January

**Comment by matejzero** [comment]
Great! Just as I go to production (finally:).

**Comment by floragunn** [comment]
If you like you can test this snapshots

https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-5/5.1.1-10-SNAPSHOT/search-guard-5-5.1.1-10-20170103.184608-7.zip

https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/dlic-search-guard-module-auditlog/5.1-4-SNAPSHOT/dlic-search-guard-module-auditlog-5.1-4-20170103.185833-8-jar-with-dependencies.jar

**Comment by matejzero** [comment]
Will try it out tomorrow and report.

Just deployed SG to production today. Had a few problems but managed to solve them rather quickly. Very happy!
