### ISSUE TITLE
Improve back pressure handling for remote calls

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-module-auditlog#7]
This affects the external ES audit log and the yet-to-be-released webhook audit log.

At the moment, we use an ExecutorService in AuditLogImpl to decouple audit log calls from external systems. This is all well, however, if there is a lot of back pressure from a busy cluster, and the external service is slow to respond, this can lead to exhausted thread pools and memory problems.

I suggest to implement a better back pressure handling and apply it to both the webhook log and the external ES log via com.floragunn.searchguard.httpclient.HttpClient. 

I've opened this issue as a start for discussing possible solutions, so anyone interested please jump in.

**Comment by floragunn** [comment]
Suggest we add a fallback which writes the auditlog messages to a file if the destination is not responsive
