### ISSUE TITLE
Filter log events for certain users

### ISSUE THREAD

**Issue by jochenkressin** [floragunncom/search-guard-module-auditlog#8]
This is actually a feature request from a customer, but I second it.

Make it possible to filter log events for certain users, like the Kibana server user or the logstash user. If you need to track all events, also AUTHENTICATED, these service users flood the audit log index with rather useless events.

We can add this for SG2 right away. For SG5 we need a new SG release, since we require a new configuration parameter.

**Comment by rptete** [comment]
yeah, i want this too

**Comment by floragunn** [comment]
merged https://github.com/floragunncom/search-guard-module-auditlog/pull/12

**Comment by floragunn** [comment]
fixed with v5 of the auditlog module
