### ISSUE TITLE
Write to date based indexes on ES

### ISSUE THREAD

**Issue by alesnav** [floragunncom/search-guard-module-auditlog#9]
Hello there!

I see that when working with `searchguard.audit.type: internal_elasticsearch` set, you can choose the index name using the variable `searchguard.audit.config.index`.

Is it possible to add date based information to the index name?

For example, I'd want to write logs to `auditlog-2017.04.18`.

Thanks,
Best regards

**Comment by floragunn** [comment]
I guess you mean "date" based (and not "data" based). 

This feature is planned an will arrive with one of the next releases.

**Comment by floragunn** [comment]
fixed with v5 of the auditlog module
